version: '3.1'

services:
  mysql-asp8:
    image: mysql:8
    container_name: mysql-asp8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: instagramar
      MYSQL_DATABASE: instagramar
    ports:
      - 3304:3306
    expose:
      - 3306
    networks:
      - instagramar

  asp:
    build: .
    container_name: asp
    ports:
      - 9000:8080
      - 9001:8081
    networks:
      - instagramar
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
    volumes:
      - /app/publish

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_insta
    depends_on:
      - mysql-asp8
    restart: always
    ports:
      - 8083:80
    environment:
      PMA_HOST: mysql-asp8
      PMA_USER: root
      PMA_PASSWORD: instagramar
      MYSQL_ROOT_PASSWORD: instagramar
    networks:
      - instagramar

networks:
  instagramar: