version: '3.1'

services:
  mysql-asp8:
    image: mysql:8
    container_name: mysql-asp8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: instagamar
      MYSQL_DATABASE: instagamar
    ports:
      - 3304:3306
    expose:
      - 3306
    networks:
      - instagamar

  asp:
    build: .
    container_name: asp
    ports:
      - 32768:32768
    networks:
      - instagamar
    volumes:
      - ./:/var/www/html/instagramar
networks:
  instagamar: