import './globals.css'
import 'react-toastify/dist/ReactToastify.css';

import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import ReduxProvider from '@/redux/provider';
import ToastifyProvider from '@/components/Toastify'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Instagramar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>

      <body className={inter.className}>
        <ReduxProvider >
          <ToastifyProvider >
            {children}
          </ToastifyProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
