import './globals.css'
import 'react-toastify/dist/ReactToastify.css';
import 'swiper/css';
import 'swiper/css/pagination';

import AuthProvider from '@/components/AuthProvider';
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import ReduxProvider from '@/redux/ReduxProvider';
import ToastifyProvider from '@/components/Toastify'

const inter = Montserrat({ subsets: ['vietnamese'] })

export const metadata: Metadata = {
  title: 'Instagramar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>

      <body className={inter.className}>
        <AuthProvider>
          <ReduxProvider >
            <ToastifyProvider >
              {children}
            </ToastifyProvider>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
