# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "devops/feature/githubaction" ]
    paths: 
      - 'Instagramar/**'
      - 'Instagramar-front/**'
  
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  # dotnet:
  #   runs-on: ubuntu-latest
  #   env:
  #     CHANGED_FILES: ${{ steps.verify-changed-files.outputs.changed_files }}

  #   defaults:
  #     run:
  #       working-directory: ./Instagramar
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v3
  #     with:
  #       dotnet-version: 8.0.x
  #   - name: Restore dependencies
  #     run: dotnet restore
  #   - name: Build
  #     run: dotnet build --no-restore
  #   - name: Test
  #     run: dotnet test --no-build --verbosity normal

  # nextjs:
  #   runs-on: ubuntu-latest
  #   env:
  #     CHANGED_FILES: ${{ steps.verify-changed-files.outputs.changed_files }}
  #   defaults:
  #     run:
  #       working-directory: ./Instagramar-front
        
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: install node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '20.x'
  #     - name: install node_modules
  #       run: npm install
  #     - name: build
  #       run: npm run build
      

